import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "../../components/navbar";
import { getCurrentUser } from "@/actions/getCurrentUser";
import { Toaster } from "react-hot-toast";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  if(!currentUser) {
    redirect('/signin')
  }

  return (
    <html lang="en">
      <body className={`${inter.className} bg-background`}>
        <Toaster />
        <div className="sticky top-0 bg-background">
          <Navbar currentUser={currentUser} />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
