import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "../../components/navbar";
import { getCurrentUser } from "@/actions/getCurrentUser";
import { IssueSheet } from "@/components/issueSheet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary text-white`}>
        <div>
          <Navbar currentUser={currentUser} />
        </div>
        <div>
          {children}
          {currentUser?.role === "USER" && (
            <div className="fixed right-8 bottom-8">
              <IssueSheet />
            </div>
          )}
        </div>
      </body>
    </html>
  );
}
